# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "006caf6da2a1471addb61c5059e3f25a"
name = "Allsteps Super"
application_url = "https://yorkshire-accountability-apache-seen.trycloudflare.com"
embedded = true

[build]
dev_store_url = "testbarinder.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://yorkshire-accountability-apache-seen.trycloudflare.com/auth/callback",
  "https://yorkshire-accountability-apache-seen.trycloudflare.com/auth/shopify/callback",
  "https://yorkshire-accountability-apache-seen.trycloudflare.com/api/auth/callback"
]
